# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c69c9d78a9dfd08eda8fa0090efd2e18ff13bca360694588bc83334fdb488982a8e2bbe76c74a86707f4bb3d00a1931544ac327bbb6b68f0329f7d39a0cf9910

test:
  secret_key_base: 9d939669765926180cfff71bb9096334cda8bc8d016a5c4614e2a9b8ea5db99f53a88812a183d9880638898830fa1bb5f9ae9e61b1479d1ccb976bf77d52bf28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
